version: '3.8'
services:
  monolith-ter:
    container_name: monolith-ter
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - OTEL_SERVICE_NAME=test-ter
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250
      - MONGODB_URI=mongodb://mongo:27017/amazon_demo
    ports:
      - "8000:8001"

  jaeger:
    container_name: jaeger-ter
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250:14250"

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana-ter
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/etc/grafana/provisioning
